### ISSUE TITLE
Cannot serialized Interpolator / CTI2D

### ISSUE THREAD

**Issue by Jammy2211** [Jammy2211/PyAutoCTI#44]
The following script shows an example of a temporal CTI model fit, with serialization of the interpolator to .json at the end:

https://github.com/Jammy2211/autocti_workspace_test/blob/main/temporal/model.py

The following line of code:

```
json_file = path.join(dataset_path, "interpolator.json")

interpolator.output_to_json(file_path=json_file)
```

Produces the following error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autocti_workspace_test/temporal/model.py", line 231, in <module>
    interpolator.output_to_json(file_path=json_file)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoConf/autoconf/dictable.py", line 123, in output_to_json
    json.dump(self.dict(), f, indent=4)
  File "/usr/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CTI2D is not JSON serializable
```

**Comment by rhayes777** [comment]
Fixed by merging autoconfig changes from last week
